pub const MAXIMUM_NUMBER_OF_VOTING_OPTIONS: usize = 3000;
pub const MAXIMUM_NUMBER_OF_SELECTABLE_VOTING_OPTIONS: usize = 120;
pub const MAXIMUM_NUMBER_OF_WRITE_IN_OPTIONS: usize = 15;
pub const MAXIMUM_WRITE_IN_OPTION_LENGTH: usize = 500;
pub const MAXIMUM_ACTUAL_VOTING_OPTION_LENGTH: usize = 50;
