// Constants from specification
pub const MAXIMUM_NUMBER_OF_SUPPORTED_VOTING_OPTIONS_N_SUP: usize = 5000;
pub const MAXIMUM_SUPPORTED_NUMBER_OF_SELECTIONS_PSI_SUP: usize = 120;
pub const MAXIMUM_SUPPORTED_NUMBER_OF_WRITE_IN_OPTIONS: usize = 30;
pub const MAXIMUM_WRITE_IN_OPTION_LENGTH: usize = 500;
pub const MAXIMUM_ACTUAL_VOTING_OPTION_LENGTH: usize = 50;
pub const CHARACTER_LENGTH_OF_UNIQUE_IDENTIFIERS: usize = 32;

/// Env Variables
pub const ENV_VERIFIER_DATASET_PASSWORD: &str = "VERIFIER_DATASET_PASSWORD";
pub const ENV_TXT_REPORT_TAB_SIZE: &str = "TXT_REPORT_TAB_SIZE";
pub const ENV_REPORT_FORMAT_DATE: &str = "REPORT_FORMAT_DATE";
pub const ENV_DIRECT_TRUST_DIR_PATH: &str = "DIRECT_TRUST_DIR_PATH";
