// Constants from specification
pub const MAXIMUM_NUMBER_OF_SUPPORTED_VOTING_OPTIONS_N_SUP: usize = 5000;
pub const MAXIMUM_SUPPORTED_NUMBER_OF_SELECTIONS_PSI_SUP: usize = 120;
pub const MAXIMUM_SUPPORTED_NUMBER_OF_WRITE_IN_OPTIONS: usize = 15;
pub const MAXIMUM_WRITE_IN_OPTION_LENGTH: usize = 500;
pub const MAXIMUM_ACTUAL_VOTING_OPTION_LENGTH: usize = 50;
